[alias]
1 = "run -p chal1"
3 = "run -p chal3"
4 = "run -p chal4 4.txt"
5 = "run -p chal5"
6 = "run -p chal6 6.txt"
7 = "run -p chal7 7.txt"
8 = "run -p chal8 8.txt"
9 = "run -p chal9"
10 = "run -p chal10 10.txt"
11 = "run -p chal11"
12 = "run -p chal12"
13 = "run -p chal13"
15 = "run -p chal15"
